### ISSUE TITLE
Crashes and fails to run

### ISSUE THREAD

**Issue by AnthonySmith01** [NativeScript/sample-ios-background-execution#1]
Tested on iOS 8 and 10, on device and simulator.

The Nativescript splash screen appears and then crashes. Error log:
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework
****\* Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x5723fc -[TNSRuntime executeModule:]
2   0x5e672 main
3   0x4a3ac9 start
JavaScript stack trace:
1   @file:///app/tns_modules/utils/utils.js:206:72
JavaScript error:
file:///app/tns_modules/utils/utils.js:206:72: JS ERROR TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)

**Comment by ivanbuhov** [comment]
@sm1ddy Make sure that you are using at least v2.3.0 of the `tns-core-modules` package.

**Comment by AnthonySmith01** [comment]
Thanks, worked for me! :)
