### ISSUE TITLE
How to set app delegate with webpack / aot

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/sample-ios-background-execution#3]
How / where to set app delegate when using webpack / aot.

**Comment by ivanbuhov** [comment]
@manojdcoder Can you give more details about the problem? How exactly the webpack bundling stops you from setting the app delegate?

**Comment by manojdcoder** [comment]
@ivanbuhov In your example, you are setting the app delegate in `main.ts`. When using webpack, `main.ts` will be invalid so I tried using `main.aot.ts`. 

But, since my app runs on both iOS and Android I had named the delegate as `custom-app-delegate.ios.ts` and soon webpack complier started throwing error in Android. So finally I managed to do that successfully inside `vendor-platform.ios.ts` then everything worked as expected.
